### ISSUE TITLE
Memory Leak & Null termination

### ISSUE THREAD

**Issue by NoakPalander** [bryangoodrich/cpp_String#1]
```
String& String::operator+= (const String& s) 
{
    unsigned len = length + s.len();
    char*    str = new char[len];

    for (unsigned j=0; j < length; j++)
        str[j] = data[j];

    for (unsigned i=0; i < s.len(); i++)
        str[length+i] = s[i];

    delete data;
    length = len;
    data   = str;
    return *this;    
}
```

When you're returning "*this" you're returning the class object "String". Which means that the valid and active char array that contains the string will be "data", so why do you not call delete[] on the temporary data ("str") ? You're allocating a new char array each time this function will be run, but you're not clearning the memory. 

Why do you not add a null termination key in the end? After you've copied the data from "str" -> "data"? 

Why do you call "delete data" instead of "delete[] data" when it's an array and why don't you allocate memory for "data"? A good rule of thumb is to always use "delete[]" when you've used "new[]".

Logically speaking it should look something like this:

```
 String& String::operator+= (const String& str)
      {
	   unsigned len = m_Size + str.size();
	     char* temp_str = new char[len];

	for (unsigned j = 0; j < m_Size; j++)
		temp_str[j] = m_Buffer[j];

	for (unsigned i = 0; i < str.size(); i++)
		temp_str[m_Size + i] = str[i];


	delete[] m_Buffer;
	m_Size = len;

	this->m_Buffer = new char[len + 1];

	for (unsigned int i = 0; i < m_Size; i++)
	{
		m_Buffer[i] = temp_str[i];
	}

	this->m_Buffer[len] = 0;

	delete[] temp_str;
	temp_str = nullptr;

	return *this;
     }
```

**Comment by SleepyMode** [comment]
You're correct about the `delete[]` part, however, I don't think there's a reason to delete the 'temporary' buffer `str`.

It's a pointer, so when you do:
```cpp
data   = str;
```

You practically make the `data` pointer point to the location in memory where `str` lies. You end up with one pointer to one place in memory. The pointer will be removed normally when the String is destructed.

I don't see where the issue is.

**Comment by NoakPalander** [comment]
Yep you're right. Delete[] is still the correct operator to call but you shouldn't delete the temporary as it's essentially "moved".

**Comment by SleepyMode** [comment]
Wow, this was a while ago. @NoakPalander surprised you still found it

**Comment by NoakPalander** [comment]
Found an "open issues" tab on github and saw that I had a bunch of open but dead issues
